// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUhJCgZiNrp3bHNj__G26a6fpM4W8QA8o',
    appId: '1:907300050462:web:6c4862e1862d5c82df400f',
    messagingSenderId: '907300050462',
    projectId: 'campus-transport-safety',
    authDomain: 'campus-transport-safety.firebaseapp.com',
    databaseURL: 'https://campus-transport-safety-default-rtdb.firebaseio.com',
    storageBucket: 'campus-transport-safety.firebasestorage.app',
    measurementId: 'G-WSBK3YNZ1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCZT-E3JddLRgOlUQa78TfsYNQkIleCyA',
    appId: '1:907300050462:android:74af460edabf16f5df400f',
    messagingSenderId: '907300050462',
    projectId: 'campus-transport-safety',
    databaseURL: 'https://campus-transport-safety-default-rtdb.firebaseio.com',
    storageBucket: 'campus-transport-safety.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBanUncCnoa0D4PmNnFJOs9ATWfRvi7LXw',
    appId: '1:907300050462:ios:1ef439b6132c3b63df400f',
    messagingSenderId: '907300050462',
    projectId: 'campus-transport-safety',
    databaseURL: 'https://campus-transport-safety-default-rtdb.firebaseio.com',
    storageBucket: 'campus-transport-safety.firebasestorage.app',
    iosBundleId: 'com.example.liveLocationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBanUncCnoa0D4PmNnFJOs9ATWfRvi7LXw',
    appId: '1:907300050462:ios:1ef439b6132c3b63df400f',
    messagingSenderId: '907300050462',
    projectId: 'campus-transport-safety',
    databaseURL: 'https://campus-transport-safety-default-rtdb.firebaseio.com',
    storageBucket: 'campus-transport-safety.firebasestorage.app',
    iosBundleId: 'com.example.liveLocationTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUhJCgZiNrp3bHNj__G26a6fpM4W8QA8o',
    appId: '1:907300050462:web:8dfb06d94fc17b49df400f',
    messagingSenderId: '907300050462',
    projectId: 'campus-transport-safety',
    authDomain: 'campus-transport-safety.firebaseapp.com',
    databaseURL: 'https://campus-transport-safety-default-rtdb.firebaseio.com',
    storageBucket: 'campus-transport-safety.firebasestorage.app',
    measurementId: 'G-PV0MKE8K9Q',
  );

}